FROM debian:bookworm

RUN apt-get update
RUN apt-get install nginx openssl --no-install-recommends --no-install-suggests -y

#COPY ./conf/nginx.conf /etc/nginx/conf.d

#CMD ["nginx", "-g", "daemon off;"]
